- name: Verificar si el servicio SSH está corriendo en el nodo
  hosts: all
  become: true
  tasks:
    - name: Verificar si el servicio SSH está corriendo
      service:
        name: ssh
        state: started
