#Ejercicio 1
#- name: Verificar si el servicio SSH está corriendo en el nodo
#  hosts: all
 # become: yes
  #tasks:
   # - name: install apache2
    #  apt:
     #    name: apache2
      #   state: present
    #- name: verificar que apache siempre este up
     # service:
      #  name: apache2
       # state: started
        #enabled: yes

#Ejercicio 2
#DEFINIENDO EL ALCANCE DE LOS HOST
- name: Deployment de un sitio web statico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el servidor es UBUNTU
      set_fact:
        # SIEMPRE QUE SEA UBUNTU
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  vars: 
    site_dir: /var/www/html/ansible_site
  tasks:
    - name: Actualilizar el cache de paquetes.
      apt:
        update_cache: yes
      when: is_ubuntu
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present
      when: is_ubuntu
    - name: verificar que apache siempre este up
      service:
        name: apache2
        state: started
        enabled: yes
      when: is_ubuntu
    - name: crear directorio para el sitio
      file:
        path: /var/www/html/ansible_site
        state: directory
        owner: www-data
        group: www-data
      when: is_ubuntu
    - name: copiar index.html al directorio del sitio
      copy:
        src: files/index.html
        dest: "{{ site_dir }}"
        owner: www-data
        group: www-data
        mode: '0644'
      when: is_ubuntu
    - name: Configuracion del sitio apache
      template:
        src: templates/ansible_site.conf.j2
        dest: /etc/apache2/sites-available/ansible_site.conf.j2
      notify:
        - Reload Apache2
      when: is_ubuntu
    - name: Desactiva el sitio por defecto
      command: a2dissite 000-default.conf
      notify:
        - Reload Apache2
      when: is_ubuntu
    - name: Activa el nuevo sitio
      command: a2ensite ansible_site.conf
      notify:
        - Reload Apache2
      when: is_ubuntu    
  handlers:
    - name: Reload Apache2
      service:
        name: Apache2
        state: reloaded